variable "aikido-role-external-id" {
  type        = string
  description = "The external ID for the IAM role - it is generated by Aikido"
}

variable "aikido-principal-arn" {
  type        = string
  default     = "arn:aws:iam::881830977366:role/service-role/lambda-aws-cloud-findings-role-uox26vzd"
  description = "aikido IAM principal to assume the role"
}

variable "aikido-principal-arn-ec2" {
  type        = string
  default     = "arn:aws:iam::881830977366:role/service-role/lambda-container-image-scanner-role-pb0qotst"
  description = "aikido IAM principal to assume the role for ECR"
}

variable "aikido-principal-arn-ecr" {
  type        = string
  default     = "arn:aws:iam::881830977366:role/aws-ebs-scanner-role"
  description = "aikido IAM principal to assume the role for ECR"
}

variable "ec2_scanner_enabled" {
  type        = bool
  default     = false
  description = "Enable EC2 scanner"
}

variable "ecr_scanner_enabled" {
  type        = bool
  default     = false
  description = "Enable ECR scanner"
}
